### ISSUE TITLE
Write a README

### ISSUE THREAD

**Issue by Zeex** [Zeex/amx_assembly#23]
^

**Comment by Y-Less** [comment]
Technically one now exists...

**Comment by Zeex** [comment]
OK then

**Comment by Y-Less** [comment]
I wouldn't say it was a good one though.  I didn't actually expect it to be closed given the current state of the readme.

**Comment by Zeex** [comment]
Sorry. I was about to say that it sucks but then I remembered that a readme is better than no readme at all...

I think when I created this issue I meant to make a readme with a high-level overview of all all modules or some kind of documentation. But it could be put in a wiki as well.

**Comment by Zeex** [comment]
I added an "Overview" section to the README. It's not complete though, I skipped some newer includes because I'm not sure what they do (like addressof). Can you please add a description for them?

**Comment by Y-Less** [comment]
Sure

**Comment by Y-Less** [comment]
Well it only took me five years to get around to that!  Done...
