### ISSUE TITLE
Not an issue, more likely an question

### ISSUE THREAD

**Issue by kubkox3** [Zeex/amx_assembly#28]
Sorry for spamming here, but I think that you could help me out. Is it possible to encode .asm file of amx back to amx format? Thank you,

**Comment by Y-Less** [comment]
As in one built with `-a`?  Or coming from amxdisasm?  It shouldn't be too hard - all the assembly and memory are done already, there's is no compilation step.  You just need an assembler, though there currently isn't one that I'm aware of.

**Comment by kubkox3** [comment]
Thank you for response, it's from amxdisasm, so I'm not gonna get it work as there's no assembler for that, right?
