### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by NemanjaMAX** [Zeex/amx_assembly#29]
I just now get NEWEST (from very VERY old) Y-Less/Y-Includes 
I get this error now, where i need to put amx_assembly.inc?
Afera Gaming by Ceta\pawno\include\YSI\..\YSI_Visual\..\YSI_Core\..\YSI_Coding\..\YSI_Core\..\YSI_Storage\..\YSI_Internal\amx_assembly.inc(38) : fatal error 111: user error: Please update "https://github.com/Zeex/amx_assembly" to get "deref()"

**Comment by Y-Less** [comment]
Did you read the error?  It tells you what to do, you don't need to put amx_assembly.inc anywhere.
